// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0--rc2
// source: shared/fraud.proto

package fraudpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FraudChecker_CheckTransaction_FullMethodName = "/fraud.FraudChecker/CheckTransaction"
)

// FraudCheckerClient is the client API for FraudChecker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FraudCheckerClient interface {
	CheckTransaction(ctx context.Context, in *FraudCheckRequest, opts ...grpc.CallOption) (*FraudCheckResponse, error)
}

type fraudCheckerClient struct {
	cc grpc.ClientConnInterface
}

func NewFraudCheckerClient(cc grpc.ClientConnInterface) FraudCheckerClient {
	return &fraudCheckerClient{cc}
}

func (c *fraudCheckerClient) CheckTransaction(ctx context.Context, in *FraudCheckRequest, opts ...grpc.CallOption) (*FraudCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FraudCheckResponse)
	err := c.cc.Invoke(ctx, FraudChecker_CheckTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FraudCheckerServer is the server API for FraudChecker service.
// All implementations must embed UnimplementedFraudCheckerServer
// for forward compatibility.
type FraudCheckerServer interface {
	CheckTransaction(context.Context, *FraudCheckRequest) (*FraudCheckResponse, error)
	mustEmbedUnimplementedFraudCheckerServer()
}

// UnimplementedFraudCheckerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFraudCheckerServer struct{}

func (UnimplementedFraudCheckerServer) CheckTransaction(context.Context, *FraudCheckRequest) (*FraudCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckTransaction not implemented")
}
func (UnimplementedFraudCheckerServer) mustEmbedUnimplementedFraudCheckerServer() {}
func (UnimplementedFraudCheckerServer) testEmbeddedByValue()                      {}

// UnsafeFraudCheckerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FraudCheckerServer will
// result in compilation errors.
type UnsafeFraudCheckerServer interface {
	mustEmbedUnimplementedFraudCheckerServer()
}

func RegisterFraudCheckerServer(s grpc.ServiceRegistrar, srv FraudCheckerServer) {
	// If the following call pancis, it indicates UnimplementedFraudCheckerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FraudChecker_ServiceDesc, srv)
}

func _FraudChecker_CheckTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FraudCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FraudCheckerServer).CheckTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FraudChecker_CheckTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FraudCheckerServer).CheckTransaction(ctx, req.(*FraudCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FraudChecker_ServiceDesc is the grpc.ServiceDesc for FraudChecker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FraudChecker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fraud.FraudChecker",
	HandlerType: (*FraudCheckerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckTransaction",
			Handler:    _FraudChecker_CheckTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shared/fraud.proto",
}
