// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.0--rc2
// source: shared/fraud.proto

package fraudpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FraudCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId uint64                 `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FraudCheckRequest) Reset() {
	*x = FraudCheckRequest{}
	mi := &file_shared_fraud_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FraudCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FraudCheckRequest) ProtoMessage() {}

func (x *FraudCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_fraud_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FraudCheckRequest.ProtoReflect.Descriptor instead.
func (*FraudCheckRequest) Descriptor() ([]byte, []int) {
	return file_shared_fraud_proto_rawDescGZIP(), []int{0}
}

func (x *FraudCheckRequest) GetTransactionId() uint64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *FraudCheckRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FraudCheckRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type FraudCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FraudScore    float64                `protobuf:"fixed64,1,opt,name=fraud_score,json=fraudScore,proto3" json:"fraud_score,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "safe" or "suspicious"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FraudCheckResponse) Reset() {
	*x = FraudCheckResponse{}
	mi := &file_shared_fraud_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FraudCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FraudCheckResponse) ProtoMessage() {}

func (x *FraudCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_fraud_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FraudCheckResponse.ProtoReflect.Descriptor instead.
func (*FraudCheckResponse) Descriptor() ([]byte, []int) {
	return file_shared_fraud_proto_rawDescGZIP(), []int{1}
}

func (x *FraudCheckResponse) GetFraudScore() float64 {
	if x != nil {
		return x.FraudScore
	}
	return 0
}

func (x *FraudCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_shared_fraud_proto protoreflect.FileDescriptor

const file_shared_fraud_proto_rawDesc = "" +
	"\n" +
	"\x12shared/fraud.proto\x12\x05fraud\"k\n" +
	"\x11FraudCheckRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\x04R\rtransactionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"M\n" +
	"\x12FraudCheckResponse\x12\x1f\n" +
	"\vfraud_score\x18\x01 \x01(\x01R\n" +
	"fraudScore\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2W\n" +
	"\fFraudChecker\x12G\n" +
	"\x10CheckTransaction\x12\x18.fraud.FraudCheckRequest\x1a\x19.fraud.FraudCheckResponseB\x10Z\x0eshared/fraudpbb\x06proto3"

var (
	file_shared_fraud_proto_rawDescOnce sync.Once
	file_shared_fraud_proto_rawDescData []byte
)

func file_shared_fraud_proto_rawDescGZIP() []byte {
	file_shared_fraud_proto_rawDescOnce.Do(func() {
		file_shared_fraud_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_fraud_proto_rawDesc), len(file_shared_fraud_proto_rawDesc)))
	})
	return file_shared_fraud_proto_rawDescData
}

var file_shared_fraud_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shared_fraud_proto_goTypes = []any{
	(*FraudCheckRequest)(nil),  // 0: fraud.FraudCheckRequest
	(*FraudCheckResponse)(nil), // 1: fraud.FraudCheckResponse
}
var file_shared_fraud_proto_depIdxs = []int32{
	0, // 0: fraud.FraudChecker.CheckTransaction:input_type -> fraud.FraudCheckRequest
	1, // 1: fraud.FraudChecker.CheckTransaction:output_type -> fraud.FraudCheckResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_fraud_proto_init() }
func file_shared_fraud_proto_init() {
	if File_shared_fraud_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_fraud_proto_rawDesc), len(file_shared_fraud_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_fraud_proto_goTypes,
		DependencyIndexes: file_shared_fraud_proto_depIdxs,
		MessageInfos:      file_shared_fraud_proto_msgTypes,
	}.Build()
	File_shared_fraud_proto = out.File
	file_shared_fraud_proto_goTypes = nil
	file_shared_fraud_proto_depIdxs = nil
}
